image:https://m-m-m.github.io/logo.svg[logo,width="150",link="https://m-m-m.github.io"]

image:https://img.shields.io/github/license/m-m-m/property.svg?label=License["Apache License, Version 2.0",link=https://github.com/m-m-m/property/blob/master/LICENSE]
image:https://github.com/m-m-m/property/actions/workflows/build.yml/badge.svg["Build Status",link="https://github.com/m-m-m/property/actions/workflows/build.yml"]

= mmm-property

image:https://img.shields.io/maven-central/v/io.github.m-m-m/mmm-property.svg?label=Maven%20Central["Maven Central",link=https://search.maven.org/search?q=g:io.github.m-m-m]
image:https://javadoc.io/badge2/io.github.m-m-m/mmm-property/javadoc.svg["base JavaDoc", link=https://javadoc.io/doc/io.github.m-m-m/mmm-property]

The module `io.github.mmm.property` (artifactId `mmm-property`) brings extended property support based on https://github.com/m-m-m/value[`mmm-value-observable`].
It was inspired from JavaFx, but as JavaFx properties are bundled with a GUI framework, projects do not want to dependend on it if they are not using JavaFx.
Further JavaFx properties are lacking some features so we reimplemented the whole thing from scratch.

== Features

* Property with name, value, type, optional metadata
* Ability to add listeners or bindings
* Properties for all common Java datatypes
* Easily extendable for custom types
* Type of property can be retrieved even if value is null
* Build-in validation support
* Build-in marshalling support for mapping from/to JSON or XML

== Usage

Maven Dependency:
```xml
<dependency>
  <groupId>io.github.m-m-m</groupId>
  <artifactId>mmm-property</artifactId>
  <version>${mmm.property.version}</version>
</dependency>
```

Module Dependency:
```java
  requires transitive io.github.mmm.property;
```

= mmm-property-builder

image:https://img.shields.io/maven-central/v/io.github.m-m-m/mmm-property-builder.svg?label=Maven%20Central["Maven Central",link=https://search.maven.org/search?q=g:io.github.m-m-m]
image:https://javadoc.io/badge2/io.github.m-m-m/mmm-property-builder/javadoc.svg["base JavaDoc", link=https://javadoc.io/doc/io.github.m-m-m/mmm-property-builder]

The module `io.github.mmm.property.builder` (artifactId `mmm-property-builder`) brings comfortable builders to build properties from `mmm-property` with https://github.com/m-m-m/validation[validation] and https://github.com/m-m-m/nls[nls].

== Features

* Individual builder per property with suffix `Builder` (e.g. `StringPropertyBuilder`).
* `StandardPropertyBuilders` to compose all builders in a single API

== Usage

Maven Dependency:
```xml
<dependency>
  <groupId>io.github.m-m-m</groupId>
  <artifactId>mmm-property-builder</artifactId>
  <version>${mmm.property.version}</version>
</dependency>
```

Module Dependency:
```java
  requires transitive io.github.mmm.property.builder;
```
